name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: [bug]
body:
	- type: textarea
		id: description
		attributes:
			label: Bug Description
			description: What happened?
			placeholder: Describe the issue clearly
		validations:
			required: true
	- type: textarea
		id: steps
		attributes:
			label: Steps To Reproduce
			description: Provide exact steps
			placeholder: "1. ...\n2. ...\n3. ..."
	- type: textarea
		id: expected
		attributes:
			label: Expected Behavior
			description: What should have happened?
	- type: textarea
		id: environment
		attributes:
			label: Environment
			description: OS, browser/version
			placeholder: "Windows 11, Edge 129"
	- type: textarea
		id: additional
		attributes:
			label: Additional Context
			description: Logs, screenshots, other details
