name: Question
description: Ask for clarification or guidance
title: "[Question]: "
labels: [question]
body:
	- type: textarea
		id: question
		attributes:
			label: Your Question
			description: What do you want to know?
			placeholder: Provide context for your question
		validations:
			required: true
	- type: textarea
		id: context
		attributes:
			label: Additional Context
			description: Logs, links, environment details
