name: Security Finding
description: Report a security alert or vulnerability that needs attention
title: "[SECURITY] "
labels: ["security", "priority: high"]
assignees:
  - isaacrlevin

body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Finding Report

        Use this template to track security findings from GHAS or other security tools.

        **For private security disclosures**, use GitHub Security Advisories instead.

  - type: dropdown
    id: source
    attributes:
      label: Source
      description: Where was this security issue detected?
      options:
        - CodeQL / Code Scanning
        - Secret Scanning
        - Dependabot
        - Manual Code Review
        - External Security Audit
        - Penetration Test
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the severity level?
      options:
        - Critical (CVSS 9.0-10.0)
        - High (CVSS 7.0-8.9)
        - Medium (CVSS 4.0-6.9)
        - Low (CVSS 0.1-3.9)
    validations:
      required: true

  - type: input
    id: alert-number
    attributes:
      label: Alert Number
      description: If from GHAS, provide the alert number
      placeholder: "e.g., #42"

  - type: input
    id: cwe-cve
    attributes:
      label: CWE / CVE
      description: Relevant CWE or CVE identifier
      placeholder: "e.g., CWE-89, CVE-2024-12345"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security issue
      placeholder: |
        What is the vulnerability?
        Where is it located?
        What is the potential impact?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be exploited?
      placeholder: |
        1. Navigate to...
        2. Enter payload...
        3. Observe result...

  - type: textarea
    id: affected-code
    attributes:
      label: Affected Code
      description: Link to or paste the vulnerable code
      render: csharp
      placeholder: |
        ```csharp
        // Vulnerable code here
        ```

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What could happen if this is exploited?
      placeholder: |
        - Data exposure
        - Unauthorized access
        - Code execution
        - Denial of service

  - type: textarea
    id: recommendation
    attributes:
      label: Recommended Fix
      description: How should this be fixed?
      placeholder: |
        Use parameterized queries instead of string concatenation...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to documentation, similar issues, etc.
      placeholder: |
        - https://cwe.mitre.org/data/definitions/89.html
        - https://docs.github.com/en/code-security

  - type: dropdown
    id: exploitability
    attributes:
      label: Exploitability
      description: How easy is it to exploit this?
      options:
        - Not Exploitable
        - Difficult (requires special conditions)
        - Moderate (requires some knowledge)
        - Easy (publicly known exploit)
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Current Status
      description: What is the current state?
      options:
        - New - Needs triage
        - Confirmed - Needs fix
        - In Progress - Being fixed
        - Fixed - Awaiting verification
        - Verified - Complete
        - False Positive
        - Won't Fix
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Remediation Checklist
      options:
        - label: Security issue confirmed
        - label: Impact assessed
        - label: Fix identified
        - label: Fix implemented
        - label: Tests added
        - label: Code reviewed
        - label: Deployed to production
        - label: Alert closed

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful

  - type: markdown
    attributes:
      value: |
        ---

        ## ⏱️ Response SLA

        Based on severity:
        - **Critical**: Fix within 1-7 days
        - **High**: Fix within 7-14 days
        - **Medium**: Fix within 14-30 days
        - **Low**: Fix within 30-90 days

        ## 📚 Resources

        - [Security Policy](../SECURITY.md)
        - [GHAS Documentation](../docs/GITHUB_ADVANCED_SECURITY.md)
        - [Vulnerable Code Examples](../src/MealPlannerApi/Examples/VulnerableCodeExamples.cs)
